### ISSUE TITLE
Modifying State Vectors

### ISSUE THREAD

**Issue by senthilarul** [mit-acl/rl_collision_avoidance#10]
Is it possible to modify the length of the state vectors, especially the "other_agents_states" vector?
I tried modifying the vector lengths and the variable definitions in Config but on running training phase 1 I observe errors showing inconsistencies in tensor length. Do I have to rerun regression before I run phase 1 training if I modify vector lengths?

**Comment by mfe7** [comment]
Yeah, because the regression step initializes the model with a given input size, you'll need to re-run regression first. And unfortunately, you'd likely need to modify the dataset that it's trying to imitate during regression, because that dataset contains (state, action, reward) tuples where state contains, in part, the original other_agents_states vector. You might be able to hack around this, e.g., by copying the existing regression dataset, modifying its shape/size, and putting dummy values in the places where you've changed the components of other_agents_states. I am pretty sure the only thing that matters for the regression phase is to get a NN that can roughly head toward the goal, and that info would be contained in the first part of the state vector. Alternatively, you might be able to skip regression, and simply initialize the NN at the start of phase 1, but I suspect the agent would never spontaneously reach the goal, and thus never get reward.

**Comment by mfe7** [comment]
I'm actually trying to modify the observation vector for a recent project, and if that works, I could point you to a branch where I made those changes, if you're interested (can't guarantee how quickly it will happen though)

**Comment by mfe7** [comment]
Hi @senthilarul i was able to get this working on a branch hosted on another remote server, but don't think I'll have time to get it integrated into this public repo. If you're interested in seeing it, please feel free to send me an email!
