### ISSUE TITLE
collision_avoidance_env.py line 356

### ISSUE THREAD

**Issue by Yuanzizizi** [mit-acl/rl_collision_avoidance#13]
rl_collision_avoidance/gym-collision-avoidance/gym_collision_avoidance/envs/collision_avoidance_env.py **line 356**

<img width="364" alt="1656837465812" src="https://user-images.githubusercontent.com/105049539/177032072-c18d92a3-16d3-4077-bfcb-748d98b07af7.png">

I suppose it should be **rewards[i] = -0.1 + dist_btwn_nearest_agent[i]/2.**

**Comment by Yuanzizizi** [comment]
Another question is

rl_collision_avoidance/ gym-collision-avoidance/ gym_collision_avoidance/ envs/ policies/ CADRL/ scripts /multi /gen_rand_testcases.py **line 214**
<img width="584" alt="屏幕截图 2022-07-04 145524" src="https://user-images.githubusercontent.com/105049539/177098528-ee9102f4-5225-40c9-bf35-759927b732d7.png">

Could you please explain why we need to make sure "straight line solution is not permitted"?

**Comment by mfe7** [comment]
Hi @TUzizi - good catch about the reward function... intuitively, + makes more sense because you'd want the penalty to decay to zero as the distance between agents gets sufficiently large. But, I think there might be a typo in some of the papers, since the original [ICRA17 paper](https://arxiv.org/pdf/1609.07845.pdf) uses - just as this code implements, but the IROS18 and Access21 use a +. I'm not 100% sure about this anymore.

For the random test case code, it's very old code that I don't suggest reading too much into. It was written ad-hoc to create some scenarios for training/testing with sufficient interaction between agents to contain useful learning signals, but sometimes also let the agents have a simple straight line path to the goal (since that's a valid real-world scenario sometimes). I think the latter is the legacy reason for the line you ask about. There are probably a lot of better ways of creating such scenarios, and maybe even cool research ideas with curriculum learning as a more principled approach.

**Comment by Yuanzizizi** [comment]
Got it. Thank you.
