### ISSUE TITLE
Question about how to train code as single agent

### ISSUE THREAD

**Issue by kmzdaniel** [mit-acl/rl_collision_avoidance#14]
Hello, Mr. Everett.
How can I run your GA3C code as single agent?
I try to changed the config(self.TRAIN_SINGLE_AGENT to True), but it is give me an error.
I need only one agent to be trained on the conditions I make for it.
so that, our agent will be trained with the "learning_ga3c" algorithm(with my policy that I make for it) and the other agents of environment using "GA3C_CADRL" method that i create the same trajectory before with "run_trajectory_dataset_creator.sh"(with GA3C_CADRL method) 
Could you please explain to me how can i do it?

**Comment by mfe7** [comment]
Hi - I haven't tried this in a while. Could you provide more info about the error you're getting? The main things that need to change for single-agent training to work would be:
- modifying the interface between the gym and RL algorithm. You could simply pass one agent's observation from gym->RL and then one agent's action from RL->gym, as is done in most RL and gym setups. I added the dictionary interface so that i could pass multiple agents' infos across that interface, but it's not needed for the single-agent training case.
- only have one agent (e.g., with index=0) use the learning_ga3c policy per episode, and give every other agent a pre-trained/defined policy

**Comment by kmzdaniel** [comment]
Thank you

**Comment by kmzdaniel** [comment]
Hi, Mr. Everett.
I changed these lines for that:
1- [self.TRAIN_SINGLE_AGENT = False](https://github.com/mit-acl/gym-collision-avoidance/blob/5dda5a2a1e146a249130a18dbbb7271f1d2c6c31/gym_collision_avoidance/envs/config.py#L89) to True

2- [88 & 89](https://github.com/mit-acl/rl_collision_avoidance/blob/5e691a14b6748a22daed3056a9be63d96f26d7a4/ga3c/GA3C/Environment.py#L89)   
self.latest_observations = observations_ & self._update_frame_q(observations_[:,1:]) 
to 
self.latest_observations = observations & self._update_frame_q(observations_[1:]) 

3- [exp = Experience(self.env.previous_state[0,I,:], action, prediction, reward, done)](https://github.com/mit-acl/rl_collision_avoidance/blob/5e691a14b6748a22daed3056a9be63d96f26d7a4/ga3c/GA3C/ProcessAgent.py#L177)  
to 
exp = Experience(self.env.previous_state[0,:], action, prediction, reward, done)

4- and I changed [test_cases.py](https://github.com/mit-acl/gym-collision-avoidance/blob/5dda5a2a1e146a249130a18dbbb7271f1d2c6c31/gym_collision_avoidance/envs/test_cases.py) to give us just one learning agent in each episode

and Then I had to train about 60 million Episodes to get a Reward of nearly 0.85 :((!!
Even when I test that checkpoint, "time to the goal" it's not as good as the multiagent network.
Did I make a mistake in those changes?

**Comment by mfe7** [comment]
Those sound like reasonable changes to make. But I'm not sure what the reason is for training on a single agent's experiences.

I also don't have good intuition for whether we should expect to achieve similar performance with training on a single agent vs. multiple agents. One downside of training on a single agent is that our reward function does not explicitly encourage cooperation (i.e., the agent could be selfish and get a better reward), whereas including multiple agents' experiences in the training batch could somehow contain information that one agent's selfish decisions impact another agent's performance.

There are much better ways to do multi agent RL nowadays. The underlying RL code here is quite old (GA3C is from ~2017 and designed for single agent RL).
