### ISSUE TITLE
How to test the ga3c-cadrl or cadrl in the gym-collision-avoidance environment?

### ISSUE THREAD

**Issue by Feng-Kaijun** [mit-acl/rl_collision_avoidance#18]

**Comment by Feng-Kaijun** [comment]
Hi, I had finished the training of ga3c-cadrl whit TrainPhase1 and TrainPhase2, but i don't understand how to test this policy, in order to fork your experience which is provided in the TABLE 1 of your latest paper (Collision avoidance in pedestrian-rich environments with deep reinforcement learning). And i am working on this survey based on your great work, especially the gym-collision-avoidance environment. Looking forward to your answers!

**Comment by mfe7** [comment]
Thanks! That is great you were able to train some new policies. There is some capability to run the trained policy in random scenarios within this repo, but I don't remember exactly how, and it sounds like you'd like to go beyond that anyway.

To test the policy as I did in the paper you referred to, I would suggest using the gym-collision-avoidance repo on its own and run [this bash script](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/experiments/run_full_test_suite.sh) (i.e., clone a fresh copy of the gym repo in a new place, since the submodule gym env within this repo is probably not as up-to-date).

That bash script should automatically run a bunch of random test scenarios for various policies and numbers of agents, based on [this config](https://github.com/mit-acl/gym-collision-avoidance/blob/6d008b93e9e2c68fdd7b4b867c63210777b6aea8/gym_collision_avoidance/envs/config.py#L254). You could edit `self.POLICIES_TO_TEST` to add a new policy key (e.g., `GA3C-CADRL-Feng`), and then add the corresponding key/value to [this dict](https://github.com/mit-acl/gym-collision-avoidance/blob/f612a44a4511b9fbeb9d6219ba81b7a70a70e793/gym_collision_avoidance/experiments/src/env_utils.py#L101) with the checkpoint path etc. To start, maybe you'll want to simply make the new policy the only element in `self.POLICIES_TO_TEST`.

This bash script should: for each number of agents, for each policy_to_test, run the same N pre-defined random test scenarios. Each test scenario will contain all agents running the same policy_to_test. Note that this config only runs 4 test cases by default, which is probably good to start with so you can be sure it's set up correctly and logs the results, but eventually increase this number (I think 500 was used in the paper?). If things are working properly, this bash script should generate a bunch of `png` files of the agent trajectories and also log some `pkl` files with results/stats of each test episode. I believe [this script](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/experiments/src/process_full_test_suite_pickles.py) is what I used to generate the numbers in the table once I had run the experiments -- running 500 experiments for each policy and each number of agents took a while (hours). Unfortunately, this last script seems to have some hard-coded paths and I am not sure it will work right away, but maybe it can be used as a guide.

Please let me know if this works or if you run into other issues!
