### ISSUE TITLE
Issue including GA3C-CADRL agents in training environment

### ISSUE THREAD

**Issue by SacheetA** [mit-acl/rl_collision_avoidance#24]
In the current code, I have seen that {non-ccoperative policy, static policy, learning policy} are included in the environment while training. I tried to include GA3C-CADRL policy too. But in the network initialization step of GA3CCADRL Policy, the tensorflow session takes forever to run. 
Is this something you have experimented with? I wanted to know if this was tried out before and if there are any known solutions to this problem?

**Comment by mfe7** [comment]
By forever, do you mean it takes a long time or that it never finishes? I have seen it take a long time relative to other parts of the code which slows down the training/experiments a lot. So for experiments, here's [an example](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/experiments/src/run_full_test_suite.py) of one workaround I had. On the first experiment, I instantiate a bunch of agents and initialize their networks (slow). Then after the episode, I return the agents list as `prev_agents` and then pass those to the next experiment, so that the agents already have initialized networks. It may need some modification to do this in training, e.g., variable numbers of agents, policies that change each episode, etc, but maybe this is one possible starting point?

The reason this slowdown didn't appear for the training implemented in this repo is that I don't use GA3C-CADRL policies during training, but rather make those agents have "learning" policies, meaning the policy is stored in one place elsewhere (inside the RL process), and actions are provided externally (via the actions arg of the step method), and the "learning" policy doesn't have a network initialization method it has to do

**Comment by SacheetA** [comment]
By forever to run, i mean that it never finishes, it took 25 mins but still didn't execute. The network initializes quickly, when the testing scripts are executed (full test suite, formations etc). But in the training process I cannot include trained GA3C CADRL agents because of this issue. Looks like a tensorflow session problem.

**Comment by mfe7** [comment]
ah ok. i haven't seen that issue myself.
